# Generated by Django 2.1.5 on 2020-07-18 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('starting_bid', models.FloatField()),
                ('description', models.CharField(max_length=256)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=2550)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='listings',
            field=models.ManyToManyField(related_name='comments', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='listings',
            field=models.ManyToManyField(related_name='bids', to='auctions.Listing'),
        ),
    ]
