# Generated by Django 2.1.5 on 2020-07-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200730_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listings',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.Listing'),
            preserve_default=False,
        ),
    ]
